language: python

env:
    - CONDA="python=2.7 numpy=1.7"

before_install:
   - sudo apt-get update -qq
    - URL=http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
    - wget $URL -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes
    - conda update conda
    - conda info -a
    - ENV_NAME='test-environment'
    # Customise the testing environment.
    - conda config --add channels rsignell
    - travis_retry conda create -n $ENV_NAME $CONDA pip iris pyoos folium oceans geojson ipython-notebook
    - pip install vincent
    - pip install git+https://github.com/birdage/folium.git@clustered_markers#egg=folium --upgrade
    - source activate $ENV_NAME
    # GUI
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
    - export PYTHONWARNINGS=all

script:
  - cd notebooks && nosetests --verbose --nocapture test_notebooks.py
