# Site settings.
title: SECOORA Numerical Ocean Models Skill Assessment
name: skill_score
safe: true
email: ocefpaf@gmail.com
description: "Prototypes for the SECOORA skill score exercise"
url: "http://SECOORA.github.io"
baseurl: /skill_score
twitter_username: ocefpaf
github_username:  ocefpaf

# Build settings.
layout: default
markdown: kramdown
highlighter: pygments
relative_permalinks: false
google_analytics_id: UA-9133259-16
permalink: pretty
repository: https://github.com/SECOORA/skill_score
collections:
  comparisons:
    output: true
