name: secoora
description: "Prototypes for the SECOORA skill score exercise"

url: "http://ocefpaf.github.io"
baseurl: /secoora


markdown: kramdown

#title: SECOORA Model Skill Assessment
#email: ocefpaf@gmail.com
#twitter_username: ocefpaf
#github_username:  ocefpaf

## Build settings
#layout: default
#highlighter: pygments
##relative_permalinks: false
#google_analytics_id: UA-9133259-16
#permalink: pretty
#repository: https://github.com/ocefpaf/secoora
#collections:
  #comparisons:
    #output: true
