# Site settings
title: Jekyll test
email: ocefpaf@gmail.com
description: "Jekyll test page."
baseurl: "http://ocefpaf.github.io/secoora"
url: "http://ocefpaf.github.io/secoora"
twitter_username: ocefpaf
github_username:  ocefpaf

# Build settings
markdown: kramdown
permalink: pretty
