# Site settings.
title: SECOORA Model Skill Assessment
name: secoora
safe: true
email: ocefpaf@gmail.com
description: "Prototypes for the SECOORA skill score exercise"
url: "http://ocefpaf.github.io"
baseurl: /secoora
twitter_username: ocefpaf
github_username:  ocefpaf

# Build settings.
layout: default
markdown: kramdown
highlighter: pygments
relative_permalinks: false
google_analytics_id: UA-9133259-16
permalink: pretty
repository: https://github.com/ocefpaf/secoora
collections:
  comparisons:
    output: true
